name: Mirror to private Forgejo

on:
  push:
    branches: [main]
  delete:

jobs:
  mirror_to_forgejo:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Mirror to private Forgejo
        uses: wearerequired/git-mirror-action@v1
        with:
          source-repo: "https://github.com/${{ github.repository }}.git"
          # Hier bauen wir Username und Token direkt in die URL ein:
          destination-repo: "https://henrymmey:${{ secrets.FORGEJO_TOKEN }}@forgejo.meyerwolke.de/henrymmey/nextcloud-backup.git"
